name: example
description: Example app for the JsonDynamicWidget library

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  desktop_window: ^0.4.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  json_dynamic_widget: ^3.1.1
  json_dynamic_widget_plugin_svg:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/pages/
