name: json_dynamic_widget_plugin_svg
description: A plugin to the JSON Dynamic Widget to provide SVG support to the widgets
homepage: https://github.com/peiffer-innovations/json_dynamic_widget_plugin_svg

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  flutter:
    sdk: flutter
  json_dynamic_widget: ^3.1.0
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.4
  websafe_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
