name: Flutter Publisher

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Validate
        uses: peiffer-innovations/actions-flutter-validate@v1.0.2
        with:
          flutter_package: true

      - name: Checkout Schemas
        uses: actions/checkout@v2
        with:
          repository: peiffer-innovations/flutter_json_schemas
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
          ref: gh-pages
          path: schemas

      - name: Update Schemas
        run: |
          git config --global user.email "noop@peifferinnovations.com"
          git config --global url."https://action:${{secrets.REPO_TOKEN}}@github.com/".insteadOf https://github.com/
          rm -rf schemas/schemas/json_dynamic_widget_plugin_svg
          mkdir schemas/schemas/json_dynamic_widget_plugin_svg
          cp output/* schemas/schemas/json_dynamic_widget_plugin_svg
          cd schemas
          git add .
          git commit --allow-empty -m "json_dynamic_widget_plugin_svg: schema update"
          git push origin HEAD:gh-pages
          cd ..

      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: true
          skip_test: true

      - uses: CDDelta/dart-version-auto-tag@v1.0.1
        with:
          token: ${{ secrets.REPO_TOKEN }}
